// index.html + style.css + app.js + assets/*.webp -> one self-contained file.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(HERE, '../../pamela-anggia-dewi-en.html');
const OUT_WIDGET = path.resolve(HERE, '../../pamela-anggia-dewi-en.widget.html');

const template = fs.readFileSync(path.join(HERE, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(HERE, 'style.css'), 'utf8');
const js = fs.readFileSync(path.join(HERE, 'app.js'), 'utf8');

const assetDir = path.join(HERE, 'assets');
const assets = new Map(
  fs.readdirSync(assetDir)
    .filter(f => f.endsWith('.webp'))
    .map(f => [
      f.replace(/\.webp$/, ''),
      `data:image/webp;base64,${fs.readFileSync(path.join(assetDir, f)).toString('base64')}`,
    ]),
);

const used = new Set();

// Replacements pass a FUNCTION, never a string. With a string, a `$&` inside the
// CSS or JS is read as "the matched text" and silently injects itself into the
// output. landing-page/tools/inline.mjs documents the same trap.
const html = template
  .replace('{{style}}', () => css)
  .replace('{{script}}', () => js)
  .replace(/\{\{asset:([a-z0-9-]+)\}\}/g, (_, name) => {
    const uri = assets.get(name);
    if (!uri) {
      throw new Error(`unknown asset "${name}" — assets/ has: ${[...assets.keys()].join(', ')}`);
    }
    used.add(name);
    return uri;
  });

const unused = [...assets.keys()].filter(n => !used.has(n));
if (unused.length && !process.env.SKIP_UNUSED_CHECK) {
  throw new Error(`assets never referenced: ${unused.join(', ')}`);
}

const leftover = html.match(/\{\{[^}]+\}\}/g);
if (leftover) throw new Error(`unreplaced token ${leftover[0]}`);

fs.writeFileSync(OUT, html);
const kb = fs.statSync(OUT).size / 1024;
console.log(`${path.relative(process.cwd(), OUT)}  ${kb.toFixed(0)} KB   (standalone)`);
if (kb > 600) throw new Error(`over the 600 KB budget by ${(kb - 600).toFixed(0)} KB`);

// --- variant for pasting into an Elementor HTML widget ---
//
// Head-only tags must not travel. A second <title> in the document broke link
// previews on the live site: scrapers that match <title>(.*)</title> greedily
// swept from the head's opening tag to this one's closing tag and used 84 KB of
// markup as the page title. <title> is inert for rendering, which is why the
// page looked fine — it is not inert for crawlers.
const style = html.match(/<style>[\s\S]*?<\/style>/)[0];
const script = html.match(/<script>[\s\S]*?<\/script>/)[0];
const main = html.match(/<main[\s\S]*<\/main>/)[0];
const widget = `<!--
  Pamela Anggia Dewi — paste this whole file into an Elementor HTML widget.
  Generated by landing-page/src/pamela-en/build.mjs — do not hand-edit.

  Document-level and head-only tags are deliberately absent. A second page
  title inside the document breaks link previews, and the rest is dropped by
  the parser anyway. Page title, description and og: tags belong in the head,
  set through WordPress.
  See docs/deploy/pamela-landing-page-wordpress-embed.md
-->
${style}
${main}
${script}
`;
fs.writeFileSync(OUT_WIDGET, widget);
console.log(`${path.relative(process.cwd(), OUT_WIDGET)}  ${(widget.length / 1024).toFixed(0)} KB   (paste into Elementor)`);

// Check for real tags, not substrings: both the HTML preamble above and a CSS
// comment mention these tag names in prose, and a blunt includes() flags those.
const prose = widget.replace(/<!--[\s\S]*?-->/g, '').replace(/\/\*[\s\S]*?\*\//g, '');
const forbidden = prose.match(/<\s*\/?\s*(html|head|body|title|meta)\b/i);
if (forbidden) throw new Error(`widget build still contains a ${forbidden[0]} tag`);
